name: Create a comment on new issues

on:
  issues:
    types: [opened]

jobs:
  
  comment-with-actions:
    permissions: write-all
    runs-on: ubuntu-latest 
    steps:
      - name: "dump github context"
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
          

      - name: Add comment
        uses: peter-evans/create-or-update-comment@5f728c3dae25f329afbe34ee4d08eef25569d79f
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This issue is available for anyone to work on. **Make sure to reference this issue in your pull request.** :sparkles: Thank you for your contribution! :sparkles:
  comment-with-api:
    runs-on: ubuntu-latest 
    steps:
      - name: Create Comment with API
        run: |
          gh api -X POST \
            http://api.github.com/repo/${{ORGANIZATION}/${REPOSITORY}/issues/${ISSUE_NUMBER}/comments \
            -f body="Comment but gtrom the API call not actions"

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORGANIZATION: ${{ github.events.organization.login }}
          REPOSITORY: ${{ github.event.repository.name }}
          ISSUE_NUMBER: ${{ github.event.issue.number }} 
